config/routes.rb
Dealerapp::Application.routes.draw do

  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :make, :model, :year, :body, :price, :color, :mileage

  validates :make, presence: true, length: { maximum: 50 }
  validates :model, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  NEW_CAR = -1

  def new
  	@car = Car.new
  end

  def create
  	@car = Car.new(params[:car])
  	if @car.save
  		flash[:success] = 'Successfully created car!'
  		redirect_to @car
  	else
  		render 'new'
  	end
  end

  def index
  	@cars = Car.paginate(page: params[:page])
  end

  def show
  	@car = Car.find(params[:id])
  end

  def edit
  	@car = Car.find(params[:id])
  end

  def update
  	@car = Car.find(params[:id])
  	if @car.update_attributes(params[:car])
      #@user.update_attribute(:member_type, params[:user][:member_type])
  		flash[:success] = "Updated!"
  		redirect_to @car
  	else
  		render 'edit'
  	end
  end

  def destroy
  	Car.find(params[:id]).destroy
    flash[:success] = "Car removed!"
    redirect_to cars_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<li>
	<span class="content">
  		<strong><%= link_to car.make + " - " + car.model, car %></strong> 
  	</span>
  	<span class="timestamp">
  		Year: <%= car.year %> <br>
  	</span>
  	Color: <%= car.color %> | Body Style: <%= car.body %> | 

<% if (car.mileage.to_i >= 0) %>
  Mileage: <%= car.mileage %>
<% else %>
  <b><font color="green">New Car</font></b> 
<% end %>

     <br>

  	<%= link_to "edit", edit_car_path(car) %> 
  	| <%= link_to "delete", car, method: :delete, confirm: "Delete this car?" %>

</li>

app/views/cars/edit.html.erb
<% provide(:title, 'Add new car') %>

<h1>Update car</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@car) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :make %>
      <%= f.text_field :make %> <br />

      <%= f.label :model %>
      <%= f.text_field :model %> <br />

      <%= f.label :year %>
      <%= f.text_field :year %> <br />

<!--
      <%= label_tag 'Signup Authorization Code' %>
      <%= text_field_tag :authorization_code %>
-->
      <%= f.label :body %>
      <%= f.text_field :body %> <br />

      <%= f.label :price %>
      <%= f.text_field :price %> <br />

      <%= f.label :color %>
      <%= f.text_field :color %> <br />

      <br /> If new car, enter -1, else enter actual mileage.
      <%= f.label :mileage %>
      <%= f.text_field :mileage %> <br />

      <%= f.submit "Update this car", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<% provide(:title, 'cars') %>

<div class="row">

	<div class="span8">

		<div class="dealernav"><h1>All Cars</h1></div>

		<%= will_paginate @cars %>

		<ul class="cars">
		  <%= render @cars %>
		</ul>

		<%= will_paginate @cars%>

		<%= button_to "New Car", new_car_path, class: "btn btn-large btn-primary", method: :get %>

	</div>

</div>

app/views/cars/new.html.erb
<% provide(:title, 'Add new car') %>

<h1>Create new car</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@car) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :make %>
      <%= f.text_field :make %> <br />

      <%= f.label :model %>
      <%= f.text_field :model %> <br />

      <%= f.label :year %>
      <%= f.text_field :year %> <br />

<!--
      <%= label_tag 'Signup Authorization Code' %>
      <%= text_field_tag :authorization_code %>
-->
      <%= f.label :body %>
      <%= f.text_field :body %> <br />

      <%= f.label :price %>
      <%= f.text_field :price %> <br />

      <%= f.label :color %>
      <%= f.text_field :color %> <br />

      <br /> If new car, enter -1, else enter actual mileage.
      <%= f.label :mileage %>
      <%= f.text_field :mileage %> <br />

      <%= f.submit "Create this car", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<b><u><h1>DISPLAY CAR</h1></u></b><br />

<h2><%= @car.make %> - <%= @car.model %></h2>

<center>
Year: <%= @car.year %> <br />
Body Style: <%= @car.body %> <br />
Color: <%= @car.color %> <br />

<% if (@car.mileage.to_i >= 0) %>
	Mileage: <%= @car.mileage %>
<% else %>
	<b><font color="green">New Car</font></b> 
<% end %>
<br />

Price: <%= @car.price %> <br />

<%= button_to "Back to List", cars_path, class: "btn btn-large btn-primary", method: :get %>

</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealerapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	

	<div class="container">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>
	</div>

	<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>